server.port=8081
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Form validation rules
form.validation.rules=
  * * * * 30,
  by * * * 90,
  by work no yes 180,
  by work no family 180,
  * * yes * 120,
  * * family * 90
